all:
  vars:
    ansible_user: ubuntu
  children:
    load_balancers:
      hosts:
        lb01:
          ansible_host: 10.30.10.11
    app:
      hosts:
        app01:
          ansible_host: 10.30.20.21
        app02:
          ansible_host: 10.30.20.22
    databases:
      hosts:
        db01:
          ansible_host: 10.30.30.31
    cache:
      hosts:
        redis01:
          ansible_host: 10.30.40.41
    monitoring:
      hosts:
        monitoring01:
          ansible_host: 10.30.50.51
    docker_hosts:
      children:
        load_balancers: {}
        app: {}
        databases: {}
        cache: {}
        monitoring: {}
