all:
  vars:
    ansible_user: ubuntu
    ansible_python_interpreter: /usr/bin/python3
  children:
    load_balancers:
      hosts:
        lb01:
          ansible_host: 192.168.56.11
    app:
      hosts:
        app01:
          ansible_host: 192.168.56.21
        app02:
          ansible_host: 192.168.56.22
    databases:
      hosts:
        db01:
          ansible_host: 192.168.56.31
    cache:
      hosts:
        redis01:
          ansible_host: 192.168.56.41
    monitoring:
      hosts:
        monitoring01:
          ansible_host: 192.168.56.51
    docker_hosts:
      children:
        load_balancers: {}
        app: {}
        databases: {}
        cache: {}
        monitoring: {}
