events {}

http {
  upstream products { server product-service:8000; }
  upstream users { server user-service:8000; }
  upstream orders { server order-service:8000; }

  server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /products { proxy_pass http://products; }
    location /users { proxy_pass http://users; }
    location /orders { proxy_pass http://orders; }
    location /health {
      return 200 'gateway healthy\n';
      add_header Content-Type text/plain;
    }
    location / { try_files $uri $uri/ /index.html; }
  }
}
