---
- name: Install Docker packages
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: Enable Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Add application user to docker group
  ansible.builtin.user:
    name: "{{ app_user }}"
    groups: docker
    append: true
